Add profile
Bearsie/medical-shepherd pull request #27
Opened 2019-06-27 08:29 UTC by grzegorzroczniak555

2019-06-27 20:27 UTC, Bearsie commented
Nie potrzebujemy pliku package-json.lock.

2019-06-27 20:29 UTC, Bearsie commented on package.json
> +    "@material-ui/core": "^4.1.1",
Do wyrzucenia, bo i tak nie używasz.

2019-06-29 19:57 UTC, Bearsie requested changes

2019-06-29 19:57 UTC, Bearsie commented on package.json
> +    "@material-ui/lab": "^4.0.0-alpha.16",
Tu podobnie, do wyrzucenia, bo i tak nie używasz.

2019-06-29 19:57 UTC, Bearsie commented on src/components/pages/Profile.jsx
> +      <div className={mergeStyles({ width: '400px', height: '70px' })}>
W jakim celu tu i w innych miejscach ustawiasz na sztywno szerokość?

2019-06-29 19:57 UTC, Bearsie commented on src/components/pages/Profile.jsx
> +  const [age, setAge] = React.useState(18);
Zamiast używać tyle razy `useState` mógłbyś stworzyć hooka i zapisać tak:
```  
const commonRisks = [
  'Aortic aneurysm',
  'Asthma',
  'Atherosclerosis',
  'Chronic obstructive pulmonary disease',
  'Contact lenses',
  'Coronary disease',
  'Diabetes',
  'Frequent alcohol consumption',
  'Hemophilia',
  'High cholesterol',
  'Hypertension',
  'Peripheral vascular disease',
  'Smoking',
];

const useSelectValue = (initialSelectValue) => {
  const [value, setValue] = useState(initialSelectValue);

  const handleChange = (val) => {
    setValue(val);
  };

  return { value, onChange: handleChange };
};
```
a w komponencie:
```
  const age = useSelectValue(52);
  const weight = useSelectValue(95);
  const height = useSelectValue(180);
  const sex = useSelectValue('Male');
  const place = useSelectValue('Europe');
  const risks = reduce(commonRisks, (currentRisks, risk) => ({
    ...currentRisks,
    [risk]: useSelectValue('Unknown'),
  }), {});
```

2019-06-29 19:57 UTC, Bearsie commented on src/components/pages/Profile.jsx
> +  <div className={mergeStyles({ width: '400px', height: '20px' })}>
Tego nie potrzebujesz.

2019-06-29 19:57 UTC, Bearsie commented on src/components/pages/Profile.jsx
> +  </div>
To wszystko jesteś w stanie zastąpić tworząc pomocniczy komponent:
```
const RadioSelect = ({ title, select, options }) => (
  <List className="no-margin">
    <ListItem title={title} smartSelect smartSelectParams={{ openIn: 'sheet' }}>
      <select name={title} {...select}>
        {map(options, (option) => (
          <option key={option} value={option}>{option}</option>
        ))}
      </select>
    </ListItem>
  </List>
);

RadioSelect.propTypes = {
  options: PropTypes.array,
  select: PropTypes.object,
  title: PropTypes.string,
};
```

a w komponencie:
```
        <BlockTitle className="text-color-primary">Common risks:</BlockTitle>
        {map(commonRisks, (riskName) => (
          <RadioSelect
            key={riskName}
            title={riskName}
            select={risks[riskName]}
            options={['Yes', 'No', 'Unknown']}
          />
        ))}  <BlockTitle className="text-color-primary">Common risks:</BlockTitle>
        {map(commonRisks, (riskName) => (
          <RadioSelect
            key={riskName}
            title={riskName}
            select={risks[riskName]}
            options={['Yes', 'No', 'Unknown']}
          />
        ))}
```

2019-06-29 19:57 UTC, Bearsie commented on src/components/pages/Profile.jsx
> +      <Col className={mergeStyles({ textAlign: '-webkit-center'})}>
Zamiast w kolumnie lepiej by było w PageContent umieścić:
```
<PageContent className="no-padding">
  ...
  ...
  ...
</PageContent>
```

2019-06-29 19:57 UTC, Bearsie commented on src/components/pages/Profile.jsx
> +    <List>
To możesz zastąpić używając tego komponentu RadioSelect, który wyżej ci pokazałem.
```
        <RadioSelect
          title="Place of Residence"
          select={place}
          options={[
            'United States or Canada',
            'Latin or South America',
            'Europe',
            'Northern Africa',
            'Central Africa',
            'Southern Africa',
            'Australia and Oceania',
            'Russia, Kazakhstan or Mongolia',
            'Southwestern Asia',
          ]}
        />
```

2019-06-29 19:57 UTC, Bearsie commented on src/components/pages/Profile.jsx
> +  <div className={mergeStyles({ width: '300px', height: '70px' })}>
To możesz zastąpić jedną linią:
```
<RadioSelect title="Sex" select={sex} options={['Male', 'Female']} />
```

2019-06-29 19:57 UTC, Bearsie commented on src/components/pages/Profile.jsx
> +    <div className={mergeStyles({ width: '300px', height: '100px' })}>
Dla poprawy czytelności kodu proponuję dodać taki komponent:
```
const RangeSelect = ({ title, value, onChange, range: [min, max], step = 1 }) => (
  <>
    <BlockTitle>
      <b>{`${title}: `}</b>{value}
    </BlockTitle>
    <List simpleList className="no-margin">
      <ListItem>
        <ListItemCell className="flex-shrink-3">
          <Range
            min={min}
            max={max}
            step={step}
            value={value}
            label={true}
            color="color-theme-primary"
            onRangeChanged={onChange}
          />
        </ListItemCell>
      </ListItem>
    </List>
  </>
);

RangeSelect.propTypes = {
  onChange: PropTypes.func,
  range: PropTypes.array,
  step: PropTypes.number,
  title: PropTypes.string,
  value: PropTypes.number,
};
```

W tym przypadku użycie będzie takie:

```
<RangeSelect title="Age" {...age} range={[18, 122]} />
```

2019-06-29 19:57 UTC, Bearsie commented on src/components/pages/Profile.jsx
> +    <div className={mergeStyles({ width: '300px', height: '100px' })}>
To będziesz mógł zastąpić tym:
```
<RangeSelect title="Weight" {...weight} range={[30, 300]} />
```

2019-06-29 19:57 UTC, Bearsie commented on src/components/pages/Profile.jsx
> +            <ListItemCell className="width-auto flex-shrink-0">
To (`<ListItemCell className="width-auto flex-shrink-0">` wygląda, że nie jest potrzebne nam.

2019-06-29 19:57 UTC, Bearsie commented on src/components/pages/Profile.jsx
> +                onRangeChange={setHeight.bind(this)}
W celu poprawy performencu proponuję zmienić na `onRangeChanged`, wtedy zmienia stan zakonczy przesuwanie

2019-06-29 19:57 UTC, Bearsie commented on src/components/pages/Profile.jsx
> +                onRangeChange={setWeight.bind(this)}
Tej funkcji nie trzeba bindować.

2019-06-30 19:12 UTC, grzegorzroczniak555 commented on package.json
> +    "@material-ui/lab": "^4.0.0-alpha.16",
Usunąłem.

2019-06-30 19:14 UTC, grzegorzroczniak555 commented on src/components/pages/Profile.jsx
> +      <div className={mergeStyles({ width: '400px', height: '70px' })}>
Myślałem, że to jedyna opcja żeby dostosować do rozmiaru telefonu. Już dostosowane bez ustawiania na sztywno.

2019-06-30 19:15 UTC, grzegorzroczniak555 commented on src/components/pages/Profile.jsx
> +  const [age, setAge] = React.useState(18);
Zrobione.

2019-06-30 19:15 UTC, grzegorzroczniak555 commented on src/components/pages/Profile.jsx
> +  </div>
Dzięki za podpowiedź, zrobione.

2019-06-30 19:16 UTC, grzegorzroczniak555 commented on src/components/pages/Profile.jsx
> +    <div className={mergeStyles({ width: '300px', height: '100px' })}>
Dodane.

2019-06-30 19:17 UTC, grzegorzroczniak555 commented on src/components/pages/Profile.jsx
> +            <ListItemCell className="width-auto flex-shrink-0">
Usunięte.

2019-06-30 19:17 UTC, grzegorzroczniak555 commented on src/components/pages/Profile.jsx
> +                onRangeChange={setWeight.bind(this)}
Ok, zapamiętam.

2019-06-30 19:18 UTC, grzegorzroczniak555 commented on src/components/pages/Profile.jsx
> +                onRangeChange={setHeight.bind(this)}
No lepsza opcja, zrobione.

2019-06-30 19:56 UTC, Bearsie approved these changes

2019-06-30 21:19 UTC, merged